
service: pawsometime-backend-meetups

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-west-2
  memorySize: 512
  environment:
    TIP_POSTS_TABLE: pawsometime-backend-posts-tip
    QNA_POSTS_TABLE: pawsometime-backend-posts-qna
    TRADE_POSTS_TABLE: pawsometime-backend-posts-trade
    GENERAL_POSTS_TABLE: pawsometime-backend-posts-general
    MEETUPS_TABLE: pawsometime-backend-meetups-meetups
    USERS_TABLE: pawsometime-backend-users-users
    NEWS_TABLE: pawsometime-backend-others-news
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TIP_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.QNA_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GENERAL_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MEETUPS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NEWS_TABLE}"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: 
        - "*"

functions:
  # meetups endpoints
  createMeeups:
    handler: meetups/create.create
    events:
      - http:
          path: meetups
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

  listMeeups:
    handler: meetups/list.list
    events:
      - http:
          path: meetups
          method: get
          cors: true

  getMeeups:
    handler: meetups/get.get
    events:
      - http:
          path: meetups/{id}
          method: get
          cors: true

  updateMeeups:
    handler: meetups/update.update
    events:
      - http:
          path: meetups/{id}
          method: put
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC
  
  deleteMeeups:
    handler: meetups/delete.delete
    events:
      - http:
          path: meetups/{id}
          method: delete
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

  autoJoinMeeups:
    handler: meetups/join.autoJoin
    events:
      - http:
          path: meetups/{id}/join
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC
            
  requestJoinMeeups:
    handler: meetups/join.request
    events:
      - http:
          path: meetups/{id}/request
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

  acceptJoinMeeups:
    handler: meetups/join.accept
    events:
      - http:
          path: meetups/{id}/accept
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC
  
  rejectJoinMeeups:
    handler: meetups/join.reject
    events:
      - http:
          path: meetups/{id}/reject
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

resources:
  Resources:
    # meetups table
    MeetupsDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.MEETUPS_TABLE}
    