
service: pawsometime-backend-gallery

provider:
  name: aws
  runtime: nodejs12.x
  profile: serverless-admin
  region: us-west-2
  memorySize: 512
  environment:
    TIP_POSTS_TABLE: pawsometime-backend-posts-tip
    QNA_POSTS_TABLE: pawsometime-backend-posts-qna
    TRADE_POSTS_TABLE: pawsometime-backend-posts-trade
    GENERAL_POSTS_TABLE: pawsometime-backend-posts-general
    MEETUPS_TABLE: pawsometime-backend-meetups-meetups
    USERS_TABLE: pawsometime-backend-users-users
    HISTORY_TABLE: pawsometime-backend-others-history
    NEWS_TABLE: pawsometime-backend-others-news
    GALLERY_TABLE: pawsometime-backend-others-gallery
    S3_BUCKET: pawsometime-serverless-s3
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TIP_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.QNA_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.TRADE_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GENERAL_POSTS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.MEETUPS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.USERS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.HISTORY_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.NEWS_TABLE}"
        - "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.GALLERY_TABLE}"
    - Effect: Allow
      Action:
        - "s3:*"
      Resource: 
        - "*"

functions:
  # gallery endpoints
  createGallery:
    handler: gallery/create.create
    events:
      - http:
          path: gallery
          method: post
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

  listGallery:
    handler: gallery/list.list
    events:
      - http:
          path: gallery
          method: get
          cors: true

  getGallery:
    handler: gallery/get.get
    events:
      - http:
          path: gallery/{id}
          method: get
          cors: true

  updateGallery:
    handler: gallery/update.update
    events:
      - http:
          path: gallery/{id}
          method: put
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC
  
  deleteGallery:
    handler: gallery/delete.delete
    events:
      - http:
          path: gallery/{id}
          method: delete
          cors: true
          authorizer:
            name: cognito-token-authorization
            arn: arn:aws:cognito-idp:us-west-2:095515517792:userpool/us-west-2_blgzK1ffC

resources:
  Resources:
    # Gallery table
    GalleryDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: id
            AttributeType: S
        KeySchema:
          -
            AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.GALLERY_TABLE}
    